import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { webcrypto } from 'node:crypto';
const values = new Map();
globalThis.localStorage = { getItem: k => values.get(k) ?? null, setItem: (k,v) => values.set(k,v), removeItem: k => values.delete(k) };
globalThis.window = { crypto: webcrypto, INITIAL_STATE: { book: null, myQuotes: [] } };
await import('../docs/readinggo/js/datastore.js');
const local = window.LocalDataStore;
local.local.configure({ storageKey: 'rg_dev_review_persona_privacy-test', initialState: { user_books: [], settings: {}, pending: {}, streak: {}, claps: {}, bookmarks: {}, wish_books: [] } });
const book = local.myBooks.add({ book: { title: 'Test' } });
assert.equal(book.visibility, 'private');
const quote = local.sentences.add({ userBookId: book.id, text: 'Quote', my_note: 'Q. SECRET A. SECRET', visibility: 'public' });
assert.equal(quote.visibility, 'private');
assert.equal(local.sentences.setVisibility, undefined);
assert.equal(local.sentences.feed().length, 0);
local.sentences.setThought(quote.id, 'Explicit thought');
local.sentenceConversations.add(quote.id, { role: 'assistant', content: 'PRIVATE TURN' });
const first = local.myBooks.setVisibility(book.id, 'public', { requestId: 'r1', expectedRevision: 0 });
assert.equal(first.revision, 1);
assert.equal(local.sentences.listByBook(book.id)[0].visibility, 'public');
const output = JSON.stringify(local.sentences.feed());
assert.ok(output.includes('Explicit thought'));
assert.ok(!output.includes('SECRET') && !output.includes('PRIVATE TURN') && !output.includes('session_id'));
assert.throws(() => local.sentences.importExisting({ userBookId: book.id, text: 'Import' }), /import_requires_private_book/);
local.myBooks.setVisibility(book.id, 'private', { requestId: 'r2', expectedRevision: 1 });
assert.equal(local.myBooks.setVisibility(book.id, 'public', { requestId: 'r1', expectedRevision: 0 }).canShare, false);
assert.throws(() => local.myBooks.setVisibility(book.id, 'public', { expectedRevision: 0 }), /revision_conflict/);
assert.equal(local.sentenceConversations.list(quote.id)[0].content, 'PRIVATE TURN');
let state = { id: 'book', visibility: 'private', revision: 0 };
let loseResponse = false;
const calls = [];
window.RG_SB = { client: () => ({ rpc: async (name,args) => {
  calls.push({ name, args });
  if (name === 'book_visibility_owner') return { data: { ...state } };
  if (name === 'book_set_visibility') {
    if (loseResponse) throw new Error('network lost');
    return { data: { ...state, replayed: true, appliedRevision: 1 } };
  }
  if (name === 'book_public_quotes') return { data: [] };
  if (name === 'sentence_import_private') return { data: { id: args.p_sentence_id, user_book_id: args.p_user_book_id, created_at: args.p_created_at } };
  throw new Error('Unexpected RPC');
} }) };
await import('../docs/readinggo/js/datastore-supabase.js');
const remote = window.SupabaseDataStore;
assert.equal(remote.sentences.setVisibility, undefined);
assert.equal((await remote.myBooks.setVisibility('book', 'public', { requestId: 'request', expectedRevision: 0 })).canShare, false);
assert.equal(calls[0].args.p_expected_revision, 0);
loseResponse = true;
await assert.rejects(remote.myBooks.setVisibility('book', 'public', { requestId: 'retry', expectedRevision: 0 }), error => error.outcome === 'unknown' && error.canShare === false && error.requestId === 'retry' && error.expectedRevision === 0);
await assert.rejects(remote.myBooks.setVisibility('book', 'followers'), /invalid_visibility_request/);
state.visibility = 'unexpected';
await assert.rejects(remote.myBooks.getVisibility('book'), /book_visibility_unknown/);
state.visibility = 'private';
await remote.sentences.importExisting({ userBookId: 'book', migrationId: 'guest-sentence', text: 'Guest quote', created_at: 0 });
assert.equal(calls.findLast(call => call.name === 'sentence_import_private').args.p_created_at, '1970-01-01T00:00:00.000Z');
await assert.rejects(remote.sentences.importExisting({ userBookId: 'book', migrationId: 'bad-time', text: 'Guest quote', created_at: Number.NaN }), /invalid_import_timestamp/);
await remote.sentences.publicByBook('book', 'quote');
assert.deepEqual(calls.at(-1), { name: 'book_public_quotes', args: { p_user_book_id: 'book', p_sentence_id: 'quote', p_limit: 50, p_offset: 0 } });
const remoteSource = readFileSync(new URL('../docs/readinggo/js/datastore-supabase.js', import.meta.url), 'utf8');
assert.match(remoteSource, /async remove\(userBookId\)[\s\S]*delete\(\)\.eq\('id', userBookId\)[\s\S]*select\('id'\)\.maybeSingle\(\)[\s\S]*book_delete_not_confirmed[\s\S]*A\.profile\.update/,
  '책 삭제는 성공 readback 뒤에만 활성 선택을 바꾼다');
console.log('OK: book privacy defaults, inheritance, projections, replay, lost response, and conversation separation');
